### ISSUE TITLE
ready to use?

### ISSUE THREAD

**Issue by duller999** [nanopack/logvac#12]
Hi,

Is this project ready to use, really like the simplicity of this, looking to use this for an internal project for logging application errors?

I have followed all the documentation, I can't get this working for some reason?

Thanks
Bob

**Comment by glinton** [comment]
Yes, logvac is ready to use. We use it daily at [nanobox](https://nanobox.io) as part of the platform stack. Feel free to jump into [the slack channel](https://slack.nanoapp.io/) and message me (@glinton) for help. Or just paste your errors here.
